---
- name: Install https for apt (Debian)
  apt: name=apt-transport-https state=present

- name: Get Icinga2 Apt Key for Debian OS family
  apt_key: url={{ icinga2_key }}
           state=present

  # Debian packages require additional packages which are provided by the
  # Debian Monitoring Project repository
- name: Get Debmon Apt Key for Debian OS family (Debian)
  apt_key: url={{ icinga2_debmon_key }}
           state=present

- name: Get Icinga2 Apt Repos for Debian OS family
  apt_repository: repo='{{ item.repo }}'
                  update_cache=yes
                  state=present
  with_items: '{{ icinga2_deb_repos }}'

  # Debian packages require additional packages which are provided by the
  # Debian Monitoring Project repository
- name: Get Debmon Apt Repo for Debian OS family (Debian)
  apt_repository: repo='{{ icinga2_debmon_repo }}'
                  update_cache=yes
                  state=present

- name: Install Icinga2 on Debian OS family
  apt: pkg={{ item.package }}
       update_cache=yes
       state=latest
       install_recommends=no
  with_items: '{{ icinga2_pkg }}'

- name: Start Icinga2
  service: name=icinga2
           state=started
           enabled=yes
