---
- include: icinga2_DebianNotUbuntu_install.yml
  when: ansible_os_family == 'Debian' and ansible_distribution != 'Ubuntu'

- include: icinga2_Ubuntu_install.yml
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'

