---
- name: Install https for apt (Debian)
  apt: name=apt-transport-https state=present

- name: Get Icinga2 Apt Key for Debian OS family
  apt_key: url={{ icinga2_key }}
           state=present
  register: add_repository_key
  ignore_errors: true

- name: Add Icinga2 apt key (alternative for older systems without SNI).
  shell: "curl -sSL {{ icinga2_key }} | sudo apt-key add -"
  args:
    warn: no
  when: add_repository_key is failed

- name: Get Icinga2 Apt Repos for Debian OS family
  apt_repository: repo='{{ item.repo }}'
                  update_cache=yes
                  state=present
  with_items: '{{ icinga2_deb_repos }}'

- name: Install Icinga2 on Debian OS family
  apt: pkg={{ item.package }}
       update_cache=yes
       state=latest
       install_recommends=no
  with_items: '{{ icinga2_pkg }}'

- name: Start Icinga2
  service: name=icinga2
           state=started
           enabled=yes
