---
- name: Install Nrpe and Plugins
  apt: 
    name: "{{ item.package }}"
    state: latest
    install_recommends: no
    default_release: "{{ item.release | default(omit) }}"
  with_items: "{{ nrpe_agent_Debian }}"
  tags:
   - nrpe_agent_install

- name: Install Check_Mem_Ng on Debian
  get_url: url={{ nrpe_agent_check_mem }}
           dest={{ nrpe_agent_plugins_path }}/check_mem_ng
           mode=0755

- name: Copy Nrpe Configuration
  template: src=nrpe.cfg.j2
            dest={{ nrpe_agent_config }}
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
   - restart nagios-nrpe-server
  tags:
   - nrpe_agent_config

